framework:
  notifier:
    # #chatter_transports:
    # #    slack: '%env(SLACK_DSN)%'
    # #    telegram: '%env(TELEGRAM_DSN)%'
    # #texter_transports:
    # #    twilio: '%env(TWILIO_DSN)%'
    # #    nexmo: '%env(NEXMO_DSN)%'
    # channel_policy:
    #     # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
    #     urgent: ['email']
    #     high: ['email']
    #     medium: ['email']
    #     low: ['email']
    # admin_recipients:
    #     - { email: admin@example.com }
    texter_transports:
      twilio_sms: "twilio://AC1fbb5ea9ffd12d556edf30e576f7857e:145b0691ee6ee968a1973a1efd7896fe@default?from=+15076085816"
